# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9201:9200"
#    - "5044:5044"
#    - "5000:5000"
#    - "12202:12202"
